spring:
  datasource:
   url: jdbc:mysql://localhost:3306/my_items2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: root
   password: root

  mail:
    host: smtp.gmail.com
    username: 2021JavaForTest@gmail.com
    password: forTest2021
    port: 587
    properties:
     mail:
      smtp:
       aut: true
       starttls:
        enable: true


myitems:
  upload:
    path: C:\\Users\\Gohar\\IdeaProjects\\springMyItems\\images\\